apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-lrbr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-lrbr@sha256:17ad835aab282b40556a2ecbe05f00b0e1a6d76de7954771ec504aada8ae3a7a
        name: my-nodejs
        resources: {}
status: {}
